# Generated by Django 3.1.7 on 2021-05-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='videoId',
            field=models.CharField(max_length=256, verbose_name='영상 Id'),
        ),
    ]
