# Generated by Django 3.1.7 on 2021-05-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnerapp', '0002_auto_20210518_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=256, verbose_name='영상 Id')),
                ('username', models.CharField(max_length=10, verbose_name='이름')),
                ('userphone', models.CharField(max_length=11, verbose_name='전화번호')),
                ('similarity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='유사도')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'db_table': 'rank',
            },
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
