# Generated by Django 3.1.7 on 2021-05-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnerapp', '0004_auto_20210516_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='high_end_section',
            field=models.IntegerField(verbose_name='최고 유사도 영상 끝 구간'),
        ),
        migrations.AlterField(
            model_name='data',
            name='high_start_section',
            field=models.IntegerField(verbose_name='최고 유사도 영상 시작 구간'),
        ),
        migrations.AlterField(
            model_name='data',
            name='low_end_section',
            field=models.IntegerField(verbose_name='최저 유사도 영상 끝 구간'),
        ),
        migrations.AlterField(
            model_name='data',
            name='low_start_section',
            field=models.IntegerField(verbose_name='최저 유사도 영상 시작 구간'),
        ),
        migrations.AlterField(
            model_name='data',
            name='total_time',
            field=models.IntegerField(verbose_name='운동시간'),
        ),
    ]
