# Generated by Django 3.2 on 2021-05-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnerapp', '0003_data'),
        ('fitnerapp', '0003_statistics'),
    ]

    operations = [
    ]
